### ISSUE TITLE
Zobrazení pouze dopravy zdarma

### ISSUE THREAD

**Issue by pavelevap** [pavelevap/ceske-sluzby#107]
Patrně nefunguje omezené zobrazení dopravy zdarma, pokud je dostupná :-(

https://wordpress.org/support/topic/zobrazit-pouze-dopravu-zdarma-pokud-je-dostupna/

**Comment by lukasprelovsky** [comment]
https://docs.woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/

Snippets for WC 2.6+

**Comment by pavelevap** [comment]
Opraveno, podporujeme nové i starší verze WooCommerce + legacy metody.
