### ISSUE TITLE
GitHub Updater

### ISSUE THREAD

**Issue by novetrendy** [pavelevap/ceske-sluzby#126]
Dobrý den, bylo by možné přidat do hlavičky pluginu: 
`* GitHub Plugin URI: https://github.com/pavelevap/ceske-sluzby`
Chci místo aktualizací z WP používat plugin [GitHub Updater](https://github.com/afragen/github-updater) (kvůli novějším verzím) a bez této hlavičky to nefunguje.
Díky!
PS: Mrkněte i na můj [Pull Request](https://github.com/pavelevap/ceske-sluzby/pull/125)

**Comment by pavelevap** [comment]
Díky za tip, doplním :-)

Mám teď rozdělané dvě funkce, kvůli kterým jsem musel část pluginu "rozkopat" a přepsat, takže ještě pár dní se k tomu nedostanu, ale pak bych chtěl implementovat všechny PR...

**Comment by novetrendy** [comment]
Super, díky!

**Comment by pavelevap** [comment]
Doplněno, uvidíme, jestli to bude fungovat :-)
