### ISSUE TITLE
Jeden produkt několikrát ve feedu

### ISSUE THREAD

**Issue by josif201** [pavelevap/ceske-sluzby#135]
Dobrý den, 

díky za skvělý plugin, používám jej na několika webovkách. Chtěl bych se zeptat, jestli je možné nějaký snadným způsobem (například s pomocí nějaké filter wordpress funkce) přidat jeden woocommerce výrobek několikrát do feedu tak, aby se zobrazoval v XML souboru vícekrát? 
Totiž jeden můj klient má výrobky, které jsou na Heurece pod několika jmény (prodejci ho přejmenovali). Jednou z možností je samozřejmě přidat výrobek několikrát do WooCommerce a přesměrovat ho na ten správný. Tomu bych se ale rád vyhnul, protože to je hodně "dirty" řešení. 

Díky za odpověď. 
S pozdravem, 

Josif201

**Comment by pavelevap** [comment]
Zatím nic podobného možné není a podle mě to ani snadno přidat nelze. Ani mě nenapadá, jak to co nejlépe realizovat. Jak byste si představoval konkrétní nastavení? A ještě mě napadá, zda to Heureka nevyhodnotí jako duplicitu, když bude mít několik "různých" výrobků stejnou URL adresu (obrázky a další parametry)? Zkuste se schválně nejdříve zeptat na jejich podpoře, zda to bude možné (nebo jak takové situace obecně nejlépe řešit) než začneme něco doplňovat... Pokud to bude možné, tak to můžeme zkusit nějak implementovat...

**Comment by josif201** [comment]
Díky za odpověď, zeptám se. 
S pozdravem, 
Josif201

**Comment by josif201** [comment]
Dobrý den, 
měl jste pravdu, tady je odpověď podpory: 

Dle našich OP není možné na Heureku pomocí XML feedu synchronizovat stejný produkt několikrát. Produkty jsou párovány na základě informací uvedených ve XML feedu v PRODUCTNAME. Stává se tedy, že různé e-shopy nabízejí shodný produkt, ale jejích  popis PRODUCTNAME se liší. Na základě těchto odlišností vznikají karty s totožnými produkty, ale jiným názvem (vždy to závisí na informacích uvedených ve feedu).

Tím si myslím, že je to de facto vyřešené, protože synchronizovat jeden výrobek několikrát by bylo přímým porušením obchodních podmínek Heureka. 

S pozdravem, 

Josef Antoš

**Comment by pavelevap** [comment]
Díky, jediné co mě napadá, že můžete vyzkoušet různé názvy a nalézt ten nejlepší s největší návštěvností (nebo konverzemi), ale jinak s tím na straně pluginu asi nic moc dělat nemůžeme...
