### ISSUE TITLE
Zasielkovna .sk a .cz

### ISSUE THREAD

**Issue by smartservis** [pavelevap/ceske-sluzby#144]
Neplanujete pridat do pluginu aj podporu Zasielkovna .sk hoc aj za priplatok, ci za nutny prispevok na ucet ?

**Comment by pavelevap** [comment]
Zásilkovna určitě bude, zatím můžete zkusit samotatný plugin: #120 (nevím, zda podporuje slovenskou verzi, ale neměl by být problém si tam případně přejmenovat několik URL adres).

Podobnou issue už tu máme, v diskuzi případně prosím pokračovat tam: #15.
