### ISSUE TITLE
ERROR: This is not a valid feed.

### ISSUE THREAD

**Issue by jasomdotnet** [pavelevap/ceske-sluzby#150]
Dostal som takuto chybovy hlasku:

`ERROR: This is not a valid feed.`

ked sa pokusam otvorit

```
https://www.obchod.cz/?feed=zbozi
https://www.obchod.cz/?feed=heureka
https://www.obchod.cz/?feed=google
```

Tieto subory idu pekne:

```
https://www.obchod.cz/wp-content/zbozi.xml
https://www.obchod.cz/wp-content/pricemania.xml
```

Toto je stav systemu:
-- odstranene

**Comment by pavelevap** [comment]
@jasomdotnet: Máte na webu nějaké příspěvky? Patrně jde o chybu WordPressu 4.7, která se projevuje pouze ve chvíli, kdy na webu nejsou žádné příspěvky. I když je to chyba WP, tak se tomu pokusíme předcházet: #134.

**Comment by jasomdotnet** [comment]
Áno, to bol problém. Na webe nebol žiadny článok (post). Po pridaní aspoň jedného článku to už funguje ako má. Ďakujem.
