### ISSUE TITLE
Ako pridať do Google Feed vlastnu fixnu kategoriu produktov

### ISSUE THREAD

**Issue by jasomdotnet** [pavelevap/ceske-sluzby#151]
Ako pridať do Google Feed vlastnu fixnu kategoriu produktov (predavam jeden druh nabytku)?

Na [Google](https://support.google.com/merchants/answer/6324436?visit_id=0-636221506822798050-951066170&rd=1)  som si nasiel, ze je to kategoria [6346](http://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt)

Ja takato moznost dostupna? Ako ju nastavit? Je nejaky video navod?

**Comment by pavelevap** [comment]
Zatím tato možnost není součástí pluginu, ale můžete si to snadno nastavit přímo v administraci Google, podrobnosti zde: #89

**Comment by jasomdotnet** [comment]
Dobre, ako riesenie staci. Pripominam, ze je tam jeden koment ktory zacina takto:

`Díky, bude časem doplněno...`

:)

**Comment by pavelevap** [comment]
Ano, ale právě proto, že to jde snadno nastavit přímo u Google, tak to moc nespěchá :-)
