### ISSUE TITLE
Heureka - Meranie konverzií

### ISSUE THREAD

**Issue by tomashavlas** [pavelevap/ceske-sluzby#152]
Zdravím,
snažil som sa zapnúť meranie konverzií na heureka.sk, ale toto nefungovalo. Po bližšej investigácii som zistil, že plugin používa neplatnú URL pre meranie konverzií, momentálne plugin používa adresu
`http://heureka.sk/direct/js/ext/1-roi-async.js`
ale podľa špecifikácie od heureka.sk by mal byť použitý skript
`https://im9.cz/sk/js/ext/2-roi-async.js`

Takisto sa na stránke heureka.sa v časti meranie konverzií zobrazuje upozornenie
> Od 1.9.2015 spracovávame iba dáta zasielané prostredníctvom nového skriptu, ktorý nájdete nižšie.

Po ručnej zmene URL skriptu začali konverzie korektne nabiehať. Bol by som rád keby táto oprava bola zapracovaná do oficialnej verzie plugin-u, ak je treba môžem vytvoriť pull request s úpravou.

**Comment by pavelevap** [comment]
@tomashavlas: Díky moc, to je zajímavé. Skript se měnil opravdu od 1. září 2015, ale právě na variantu s `heureka.cz`, respektive `heureka.sk` ([zdroj](https://blog.heureka.cz/2015/07/20/skript-mereni-konverzi-se-meni/)). A v [nápovědě](https://sluzby.heureka.cz/napoveda/mereni-konverzi/) to tak také mají, tak nevím :-(

Když se ale přihlásím do Heureky, tak tam [mám](https://sluzby.heureka.cz/obchody/mereni-konverzi/) v ukázkovém kódu adresu `https://im9.cz/js/ext/1-roi-async.js` (takže `1` bude asi pro českou verzi a `2` pro slovenskou). Možná je to nová adresa pro nově registrované eshopy? Těžko říci, budeme to muset asi zjistit přímo od podpory. Teď je otázkou, zda to funguje tímto způsobem i zpětně pro všechny eshopy?

https://github.com/pavelevap/ceske-sluzby/blob/317ef2070277ecd0fb766031f74972d286d65b98/ceske-sluzby.php#L113

PR vítán, sice to vypadá, že se tu hromadí, ale mám rozdělaných několik větších věcí (EET a iDoklad), takže se na to vrhnu hned po dokončení.

**Comment by lukasprelovsky** [comment]
Ahoj, taky mi nefunguje http://heureka.sk/direct/js/ext/1-roi-async.js ale kdyz to zmenim na  https://im9.cz/sk/js/ext/2-roi-async.js uz to facha!!

I v tom implementacnim navodu uz je ta url https://im9.cz/sk/js/ext/2-roi-async.js 

vid screen

![meranie konverzii - heureka sk](https://cloud.githubusercontent.com/assets/15073394/23916785/9b65cf3c-08ed-11e7-9e96-a2e69b000514.png)

**Comment by pavelevap** [comment]
Díky, nezkoušeli jste se někdo ptát přímo na Heurece? U některých eshopů vidím v návodu starou adresu a u jiných zase novou, je to dost podivné, možná platí nová adresa pro nové registrace?

**Comment by pavelevap** [comment]
Aha, tak chybka bude v tom, že by tam asi mělo být `http://heureka.sk/direct/js/ext/2-roi-async.js` (dvojka místo jedničky). Opravím, jinak by měly fungovat oba skripty.

**Comment by pavelevap** [comment]
Kompletně jsem to změnil a skript se bude vždy načítat z nového místa `https://im9.cz`, a to jak pro českou, tak slovenskou verzi. Pokud by se objevil nějaký problém, tak dejte prosím vědět.
