### ISSUE TITLE
Do <PRODUCTNAME> v xml feedu vstupují jiné hodnoty jako materiál, barva nebo velikost produktu

### ISSUE THREAD

**Issue by qaywsxedcrfvtgb** [pavelevap/ceske-sluzby#161]
Když vygeneruji xml feed pomocí tohoto pluginu, tak v <PRODUCTNAME> jsou zobrazeny i hodnoty, které tam nepatří. Zde je příklad:
`<PRODUCTNAME>Novorozenecká košilka 100% bavlna 56</PRODUCTNAME>`
Jak vidíte, v názvu je z nepochopitelného důvodu obsažen materiál a velikost, přitom při editaci produktu je Title v pořádku a není v něm obsaženo nic jiného.

Chyba je u všech produktů v XML feedu. Vždy se do názvu zaplete jedna z vlastností produktu jako je barva, velikost, materiál, nebo i vše dohromady...

**Comment by pavelevap** [comment]
@qaywsxedcrfvtgb: Ano, to byla původní funkce, ale není to zase tak nepochopitelné :-) Předpoklad byl, že většina eshopů používá vlastnosti tak, že odpovídají požadavkům Heureky na element [PRODUCTNAME](https://sluzby.heureka.cz/napoveda/xml-feed/#PRODUCTNAME), tak byly automaticky doplňovány i do názvu.

Použijte prosím nejnovější verzi 0.6-alpha a novou funkci pro definici PRODUCTNAME: #21. Příklad je popsán zde: https://github.com/pavelevap/ceske-sluzby/issues/21#issuecomment-272965207 a http://www.separatista.net/forum/tema/xml-feed-pro-heurekacz/page/2/#post-31595

Stručně řečeno je defaultně použito nastavení `{PRODUCTNAME} | {KATEGORIE} | {NAZEV} {VLASTAXVID}`, které můžete změnit na `{PRODUCTNAME} | {KATEGORIE} | {NAZEV}` (tedy bez vlastností v názvu).

Zkuste a dejte prosím vědět, zda to funguje, díky!

**Comment by pavelevap** [comment]
Mělo by být vyřešeno a funkční.
