### ISSUE TITLE
WP-CLI nebeži pre najaku chybu v module 'ceske-sluzby'

### ISSUE THREAD

**Issue by jasomdotnet** [pavelevap/ceske-sluzby#164]
Nazdarky,
ako reprodukovat chybu:

1 . Stiahnem si WP-CLI(toris) z http://wp-cli.org/

`curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`

2. V shelly s nainšalovaným modulom 'ceske-sluzby' pustim tento command:

`php wpcli.phar plugin list`

A uvidim takúto hlášku:

```
PHP Fatal error:  Cannot use $this as parameter in /home/niekde.com/web/wp-content/plugins/ceske-sluzby/ceske-sluzby.php on line 1173
Fatal error: Cannot use $this as parameter in /home/niekde.com/web/wp-content/plugins/ceske-sluzby/ceske-sluzby.php on line 1173
```

**Comment by pavelevap** [comment]
@jasomdotnet: PHP 7.1? Podobnou chybu už tu máme: #163.

**Comment by jasomdotnet** [comment]
Presne ako píšeš:

uid134326@shellserver:~$ php -v
PHP 7.1.4-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 22:12:32) ( 
NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
     with Zend OPcache v7.1.4-1+deb.sury.org~xenial+1, Copyright (c) 
1999-2017, by Zend Technologies

**Comment by pavelevap** [comment]
Hotfix zatím zde: https://wordpress.org/support/topic/doba-dodani-pro-kazdou-variantu-zvlast/#post-9048993

Ještě chci dohledat, kde je opravdu příčina, zda PHP nebo plugin :-)

**Comment by pavelevap** [comment]
Duplicate: #163
