### ISSUE TITLE
 syntax error, unexpected '}'

### ISSUE THREAD

**Issue by mrija** [pavelevap/ceske-sluzby#177]
Parse error: syntax error, unexpected '}', expecting end of file in /..../www/wp-content/plugins/ceske-sluzby/ceske-sluzby.php on line 1534

..závorka navíc

**Comment by pavelevap** [comment]
@mrija: Díky moc, [tady](https://github.com/pavelevap/ceske-sluzby/commit/146750701bf5605ea4d805326abdb68e136f9643) se to tam dostalo, nepozornost :-(

**Comment by pavelevap** [comment]
Opraveno, ještě jednou díky: https://github.com/pavelevap/ceske-sluzby/commit/a5a7a7b0bf6a82a8744b15f68cfe85b4e2fe18a5
