### ISSUE TITLE
Chyba - Nezobrazuje sa vygenerovaný XMl Feed

### ISSUE THREAD

**Issue by Kocarik** [pavelevap/ceske-sluzby#187]
Ahoj,

Nezobrazí sa mi vygenerovaný XML Feed, dostanem len tieto chyby:

1. https://prnt.sc/gdyh1x

2. https://prnt.sc/gdygx6

**Comment by pavelevap** [comment]
@Kocarik: Máte tam nahranou nejnovější verzi `0.6-alpha` z Githubu?

**Comment by Kocarik** [comment]
@pavelevap Ano mám tam Verze 0.6-alpha .

**Comment by pavelevap** [comment]
Tak to je podivné, [pošlete](https://www.separatista.net/kontakt) prosím přístupy, budu se na to muset podívat...

**Comment by Kocarik** [comment]
Zaujimavé, ked som deaktyvoval a naspet aktyvoval tento plgin: https://codecanyon.net/item/woocommerce-currency-switcher/8085217 , tak uz feed funguje :) .

**Comment by pavelevap** [comment]
Nechám si to raději otevřené, patrně je tam nějaký konflikt, těžko říci, který plugin za to může :-(

České služby byly instalovány/aktivovány až po tomto pluginu? Neobjevila se třeba v logu nějaká chyba? Nedal by se náhodou sehnat včerejší (s chybou) a dnešní (už funkční) dump databáze, abych to mohl porovnat a podívat se, co se tam stalo?

**Comment by Kocarik** [comment]
Nem´ma zálohu, databázi, a ani pristu ku klientovmu hostingu ...

**Comment by pavelevap** [comment]
Tak s tím už asi bohužel nic neuděláme, pokud někdo narazí na podobný problém, tak se na to můžeme podívat, ale budu potřebovat podrobnosti.

Jen doplním názvy chyb, aby se to lépe hledalo:

- This XML file does not appear to have any style information associated with it. The document tree is shown bellow.
- This page contains the following errors:
error on line 1 at column 2: StartTag: Invalid element name
Bellow is a rendering of the page up to the first error.
