### ISSUE TITLE
Nefunguje na WP 4.8.2. a WC 3.2.1

### ISSUE THREAD

**Issue by petrjiricek** [pavelevap/ceske-sluzby#192]
Tak jsem to zkoušel na posledních verzích a neobjeví se to ani v menu. Zkusil jsem Plugin aktivovat / deaktivovat a neobjevil se.

**Comment by lukasprelovsky** [comment]
Na https://www.rozbisa.sk mam na takych verziach ako pises a funguje vsetko :)

**Comment by pavelevap** [comment]
@petrjiricek: Pár chybek tam s novou verzí je, ale hlavní funkčnost by měla být bez problémů. Možnosti nastavení by se měly objevit v menu WooCommerce - Nastavení - záložka České služby.

**Comment by pavelevap** [comment]
Nejnovější verze by měla fungovat všude, pokud nefunguje, tak se prosím ozvěte s podrobnostmi.
