### ISSUE TITLE
MANUFACTURER pouze v RSS nikoliv v XML souboru

### ISSUE THREAD

**Issue by cafesk8** [pavelevap/ceske-sluzby#195]
Zdravím,

v administraci si zvolím, že chci jako výrobce vypisovat štítek produktu: product_tag. Vše funguje, ale pouze v RSS feedu na adrese domain.cz/?feed=heureka nikoliv v souboru domain.cz/wp-content/heureka.xml, sem se mi tam parametr prostě nechce prospsat. Zkoušel jsem několikrát soubor přegenerovat, ale bohužel se problém nepodařilo vyřešit. Nevíte co s tím?

**Comment by cafesk8** [comment]
Chyba byla v souboru class-ceske-sluzby-xml.php na řádku 1045 a 1045, kde se ověřuje existence proměnné $vyrobce a poté se případně tato proměnná $vyrobce vypíše do XML tagu. Bohužel proměnná $vyrobce neexistuje, přepsal jsem na $vyrobce_produkt a je to funkční.

**Comment by pavelevap** [comment]
Díky moc, @cafesk8, a omluva za zpoždění!
