### ISSUE TITLE
Problém s generováním xml zbozi.cz

### ISSUE THREAD

**Issue by WeDesIn** [pavelevap/ceske-sluzby#197]
Dobrý den, 

vygenerování xml souboru pro zboží.cz mi hází následující chybu:
CHYBA: Neplatná šablona pro RSS zdroj.

Samozřejmě jsem to googlil a řešení jsem nenašel, podle toho, co se mi podařilo dohledat, by to mělo funguvat bez problémů hned po spuštění. 

Kdyžtak díky za rady!

S pozdravem, 

Josef

**Comment by pavelevap** [comment]
Problém se stále vyskytuje?

Pokud máte málo produktů, tak půjde patrně o nějaký konflikt s jiným pluginem. Zkuste všechny pluginy deaktivovat a použít základní šablonu, zda se to nezlepší (ideálně v anonymním okně prohlížeče, aby se vyloučilo cachování).

Pokud máte hodně produktů, tak používejte raději klasický `.xml` soubor, který se generuje postupně (stačí ho aktivovat v administraci).

Pokud nic nepomůže, tak se prosím [ozvěte](https://www.separatista.net/kontakt), zkusím se na to podívat. Zatím uzavírám, ale můžete znovu otevřít či doplnit komentář.
