### ISSUE TITLE
Chyba v odeslaném e-mailu o sledování zásilek

### ISSUE THREAD

**Issue by N3S4** [pavelevap/ceske-sluzby#202]
Zdravím, využívám plugin pro úpravu e-mailů - Kadence - z repozitáře wordpress. Po aktivaci českých služeb se mi po odeslání e-mailu se sledovacím odkazem v e-mailu zobrazí nad obsahem 

> Warning: Missing argument 2 for Kadence_Woomail_Designer::add_email_header(), called in /data/web/virtuals/93005/virtual/www/subdom/---/wp-includes/class-wp-hook.php on line 286 and defined in /data/web/virtuals/93005/virtual/www/subdom/---/wp-content/plugins/kadence-woocommerce-email-designer/kadence-woocommerce-email-designer.php on line 560

Nevíte, čím by to mohlo být?
Předem děkuji za případnou pomoc.

**Comment by N3S4** [comment]
Tak jsem to vyřešil, v řádku 

`do_action( 'woocommerce_email_header', $email_heading ); ?>`

jsem přidal nakonec (jako v jiných šablonách emailu) $email
`do_action( 'woocommerce_email_header', $email_heading, $email ); ?>`

**Comment by pavelevap** [comment]
Díky, nechám si to otevřené a přidám asi přímo do pluginu.
