### ISSUE TITLE
Chyba číslovanie objednávok

### ISSUE THREAD

**Issue by Kocarik** [pavelevap/ceske-sluzby#206]
Mám Woo 3.71 a ked som stiahol odtial poslednú verziu a po aktivácii modulu mi zmizlo číslovanie objednávok.

**Comment by pavelevap** [comment]
Bože, to je hloupá chybka, díky! Opravím...

**Comment by pavelevap** [comment]
To je tak, když se nová funkce pro vlastní čísla objednávek zapomene otestovat pro případ, kdy si ji někdo vůbec od počátku neaktivuje :-(

**Comment by Kocarik** [comment]
Joo Dikes :)
