### ISSUE TITLE
Wpify Woo - alternativa k pluginu České služby

### ISSUE THREAD

**Issue by vaclavgreif** [pavelevap/ceske-sluzby#220]
Vzhledem k tomu, že plugin České služby je už nějakou dobu neudržovaný, vytvořili jsme nový plugin přidávají některé z původních funkcionalit Českých služeb.

Plugin je ke stažení zdarma na https://cs.wordpress.org/plugins/wpify-woo/, možná by stálo přidat do readme?

**Comment by pavelevap** [comment]
Perfektní, díky!

Plugin České služby není mrtvý, ale bohužel je aktuálně delší dobu pozastavený, protože nemám s dětmi doma moc času na to, abych dokončil jeho větší aktualizaci (snad pandemie časem dovolí). Ale na většině webů by měl plugin fungovat i přes své stáří bez problémů. Možná tam pak ponechám jen funkce, které v tomto novém pluginu nejsou, uvidíme. Během posledních let jsem pro vlastní účely doplnil mnoho dalších funkcí, ale asi nebudou všechny zveřejněny a některé bohužel zase nejsou připravené pro obecné použití (nemají třeba možnosti nastavení, atd). Ale to všechno souvisí opět s dostupným časem :-)

**Comment by LMRig** [comment]
Tak to já zase spíš použiji České Služby, kde není rozdíl mezi premium a normal (největší svinstvo WordPress pluginů).

**Comment by vaclavgreif** [comment]
@LMRig Funkce dostupné ve WPify Woo jsou a budou dostupné zdarma, na další funkcionality vytváříme addony. 

Nevím, jakou máte zkušenost s vývojem pluginů, ale vývoj a údržba takového pluginu zabere poměrně dost času, v případě WPify Woo to jsou už stovky hodin, a dělat vše zadarmo není dlouhodobě udržitelné...:-)

**Comment by xube** [comment]
Boli časy, keď pluginy pre Wordpress boli skutočne opensource, tak ako samotný wordpress. To vytvorilo okolo wordpress základňu užívateľov, ktorí do toho boli ochotní investovať kopec času. Žiadne platené prémium neboli, a ak boli, tak s doživotnou aktualizáciou alebo viazané na online služby. Dnes je všetko len na rok a za prestrelené ceny. Čistý biznis. Takto by to nemalo vyzerať. Problém je, že vývoj pluginu zaplatí prvý klient a s jeho láskavým povolením by sa mali tieto veci šíriť ďalej, keďže aj on sám ušetril kopec tisíc, keď nemusel vyvíjať vlastný eshop. Naviac kde je pokrok v tom, že len privilegovaní môžu používať pluginy za poplatok?! Potom je to čistý kapitalizmus, kde sa dookola vymýšľa koleso pod inou značkou.

Celkovo ľudia open source znásilňujú. Už sa to deje aj na Linuxe. Dnes je Open Source jadro len lep, pre naivných užívateľov, ktorí nevidia rozdiel medzi freeware a opensource a potom ich automatickou aktualizáciou donútime platiť mesačné poplatky či iné nezmysly. Ono by bolo vporiadku programovať platené rozšírenia pre vlastné riešenia, ale parazitovať na popularite open source platformách mi príde nanajvýš otázne. Predovšetkým ak sa neodvádza aspoň časť ziskov pôvodným autorom wordpress a woocommerce. Samozrejme chápem, že ľudia si za svoje úsilie zaslúžia odmenu a že tvorba scriptov je časovo aj mentálne náročná, ale skôr ako by sa mali zamyslieť či nemizne láska z programovania a tvorenia pri tom ako sa to celé zkomercionalizuje.

Každopádne slobodne nech si každý vyberie čo potrebuje. Ak chcú ľudia špičkovú podporu a aktuálizovaný plugin, tak budú musieť využívať platené služby. Akurát by sa nemuseli tieto platené demo verzie šíriť ako free na wordpress repositary.

**Comment by vaclavgreif** [comment]
@xube Díky za názor. 

Já nikomu WPify Woo nenutím. Plugin nabízí spoustu funkcionalit zdarma, některé z nich se kryjí s pluginem České služby, proto jsem ho tu nabídl jako alternativu, která je (narozdíl od Českých služeb) aktualizovaná.

Nevím, čím se vy živíte, ale my se živíme jako WordPress programátoři, a tím pádem některé naše služby musí být placené. 

Samozřejmě ale rád využiji vašich neomezených a doživotních služeb zdarma, ať už to je cokoli, a budu na tom budovat svůj business. To je totiž to, co očekáváte od WP vývojářů.

Já si naopak myslím, že správný přístup je "To je ale skvělé, že WPify vytvořili plugin zdarma, abych je podpořil, koupím si nějaký addon".

**Comment by uhlhosting** [comment]
> @xube Díky za názor. 
> 
> 
> 
> Já nikomu WPify Woo nenutím. Plugin nabízí spoustu funkcionalit zdarma, některé z nich se kryjí s pluginem České služby, proto jsem ho tu nabídl jako alternativu, která je (narozdíl od Českých služeb) aktualizovaná.
> 
> 
> 
> Nevím, čím se vy živíte, ale my se živíme jako WordPress programátoři, a tím pádem některé naše služby musí být placené. 
> 
> 
> 
> Samozřejmě ale rád využiji vašich neomezených a doživotních služeb zdarma, ať už to je cokoli, a budu na tom budovat svůj business. To je totiž to, co očekáváte od WP vývojářů.
> 
> 
> 
> Já si naopak myslím, že správný přístup je "To je ale skvělé, že WPify vytvořili plugin zdarma, abych je podpořil, koupím si nějaký addon".

Jsi chtel rict ako pekne jsi videl kopirovat praci co nikdo zdielal uzroky v kuse pod ceske sluzby. Jsi tak chytri ze nevidis ze blbost sedi doma na postel stebou... nejsme vseci blbci ako myslis ze ako ty jsi pracoval. Ked zoberem vas modul garantujem 85% bude stejne source kod ako v ceske sluzby. Aj Prusa vzal open source tiskarnu a jsi tvoril lepsie a pak ho prodal. Ale nikde nesel a jeste jsi delal reklamu ze hele tady mate vzal sem vcera open source tiskarnu a ted je moja a ho prodam pod jmenen kokos co mu nestaci prachy ci nevie ako sa prodat ci lhat ostatnie. Nejsi ani clovek lebo abychom jsi bol clovek to je velky vec nedokaze to kazdej, hlavne ne kradeje a chytraky jak cip ako ty pane developer bez prec a daleko!

**Comment by vaclavgreif** [comment]
@uhlhosting Možná byste mohl předtím než něco napíšete do toho kódu mrknout - není tam zkopirovaná ani řádka. 😉

@pavelevap Prosím o smazání celého vlákna, tohle evidentně nemá smysl😉

**Comment by jdrda** [comment]
Já netuším, o čem se tady hádáte, jsem v oboru 23 let, nějaký OS jsem už také napsal, a je mi šumák, jestli na tom někdo vydělá. Beru to tak, že i já jsem si mohl vydělat díky spoustě OS, tak když řeším nějaký problém originálně a mám na to čas, tak to pod OS dám.

REALITA
1. české služby nemají dlouho update = stávají se pro praxi pomalu nepoužitelnými
2. WPify = je díky updatům použitelný, ale není celý zdarma

.. tak co je lepší? Kupovat celé prémiovky od Toreta, nebo si to psát sám? 

Pokud se někomu nelíbí, že jsou prémiové pluginy, tak ať je napíše pod OS, udržuje je, hlídá kompatibilitu skrz ostatní pluginy a systém, vezme si na starosti issues, prostě ať si najde čas, který si ostatní nechávají zaplatit a dělá to zdarma a pro komunitu. Však mu nic nebrání.

**Comment by uhlhosting** [comment]
Tohle je iba copie modelu toretajak vydelat penize robil to kolos musil a musil to kazdej zkopirovat od nej. Horsie developeru sa jeste v indii sa nachazi s takou mentalitu.

**Comment by morvy** [comment]
No, nahodou som sem zabludil a nestacim sa cudovat, ako nejaky hybrid medzi nemcom/slovakom/cechom/mimozemstanom dokaze urazat a nadavat na niekoho pracu bez stipky sebareflexie a triezveho pohladu na vec.
Nejdem sa zastavat ziadnej strany, ale realita je taka ze:
1. Ceske sluzby su dlhodobo bez updatov ci pridani novych funkcii, ale relativne funguju. To co ponukaju je fajn, vela ludom to staci, je to free.
2. WPify je tiez v podstate free, ponuka kopec funkcii zadarmo, hlavne tie, co ludia vyuzivaju aj v plugine Ceske sluzby. 1 modul co vzdy zakaznikom odporucam je Conditional Shipping, cim sa aj riesi podpora pre vyvojarov aby vobec mali chut nieco urobit, lebo vzdy sa da robit aj nieco ine (a ked to nechcu, ved OK, da sa to aj nakodit, ale ten cas na to potrebny presiahne cenu pluginu v 90% pripadoch!).
Ak tu niekto ide tvrdit, ze je to kopia Ceske sluzby, v zivote sa nepozrel do zdrojakov, lebo WPify je teda ina uroven OOP PHP, nevyzera to ako volnocasovy projekt, ci stredoskolska rocnikova praca, ako mnozstvo free pluginov. Ak sa bavime o kopirovani funkcionality ci myslienky, tak to uz potom vypnime internet, lebo v kazdom plugine sa da najst nieco, co sa pouzilo z ineho pluginu..
3. Toret pluginy maju kod hadam niekde z roku 2012 a len sa to lepi jedno cez druhe. Ak pride novy plugin, je to len prepouzity kod z niecoho predchadzajuceho, vacsina je platena, vacsina ma bugy ..ale da sa rozumne riesit a vyriesit problem, takze dajme tomu, ze ked uz fakt nieco od Toretu potrebujem, 60% casu sa premozem a kupim to, ale do zdrojaku sa radsej nepozeram, lebo mi je vzdy nevolno (nepaci sa mi pomer cena/kvalita, ale ked to inak nejde, pouzije sa).

**Comment by uhlhosting** [comment]
> No, nahodou som sem zabludil a nestacim sa cudovat, ako nejaky hybrid medzi nemcom/slovakom/cechom/mimozemstanom dokaze urazat a nadavat na niekoho pracu bez stipky sebareflexie a triezveho pohladu na vec.
> 
> Nejdem sa zastavat ziadnej strany, ale realita je taka ze:
> 
> 1. Ceske sluzby su dlhodobo bez updatov ci pridani novych funkcii, ale relativne funguju. To co ponukaju je fajn, vela ludom to staci, je to free.
> 
> 2. WPify je tiez v podstate free, ponuka kopec funkcii zadarmo, hlavne tie, co ludia vyuzivaju aj v plugine Ceske sluzby. 1 modul co vzdy zakaznikom odporucam je Conditional Shipping, cim sa aj riesi podpora pre vyvojarov aby vobec mali chut nieco urobit, lebo vzdy sa da robit aj nieco ine (a ked to nechcu, ved OK, da sa to aj nakodit, ale ten cas na to potrebny presiahne cenu pluginu v 90% pripadoch!).
> 
> Ak tu niekto ide tvrdit, ze je to kopia Ceske sluzby, v zivote sa nepozrel do zdrojakov, lebo WPify je teda ina uroven OOP PHP, nevyzera to ako volnocasovy projekt, ci stredoskolska rocnikova praca, ako mnozstvo free pluginov. Ak sa bavime o kopirovani funkcionality ci myslienky, tak to uz potom vypnime internet, lebo v kazdom plugine sa da najst nieco, co sa pouzilo z ineho pluginu..
> 
> 3. Toret pluginy maju kod hadam niekde z roku 2012 a len sa to lepi jedno cez druhe. Ak pride novy plugin, je to len prepouzity kod z niecoho predchadzajuceho, vacsina je platena, vacsina ma bugy ..ale da sa rozumne riesit a vyriesit problem, takze dajme tomu, ze ked uz fakt nieco od Toretu potrebujem, 60% casu sa premozem a kupim to, ale do zdrojaku sa radsej nepozeram, lebo mi je vzdy nevolno (nepaci sa mi pomer cena/kvalita, ale ked to inak nejde, pouzije sa).

Kamarade jsi co sam nevis od 
tolik chytrosty! Muj nazor je muj nazor neliby sa ty tak bez sa vyvencit asi nemas dost kysliku do mozku! Spoko jsi frajer teras, vul jedinej!
