### ISSUE TITLE
Doprava: DPD ParcelShop

### ISSUE THREAD

**Issue by novetrendy** [pavelevap/ceske-sluzby#25]
U DPD ParcelShop se nezapočítává DPH na dopravu.
Upravil jsem zakomentovaním v class-ceske-sluzby-dpd-parcelshop.php na řádku 29.

    //'calc_tax' => 'per_item'

**Comment by pavelevap** [comment]
Díky za report, původně převzato bezmyšlenkovitě :-( přímo z manuálu: https://docs.woothemes.com/document/shipping-method-api/

Defaultně je `calc_tax` nastaveno na `per_order`, ale když tam máme `per_item`, tak je předpoklad, že chceme mít daň z dopravy spočítanou na základě objednaných položek a `cost` by mělo být pole (což v tomto případě není). Časem se bude asi tato možnost [hodit](https://docs.woothemes.com/document/per-product-shipping/), ale zatím máme pouze jednoduché nastavení ceny dopravy pro celou objednávku, což způsobuje jen problémy s daněmi.

Opraveno: https://github.com/pavelevap/ceske-sluzby/commit/337624010b67a702bc44c99a2378d1c03531c05a

Prosím o vyzkoušení!

**Comment by pavelevap** [comment]
@novetrendy: Oprava funguje? Můžeme to uzavřít?

**Comment by novetrendy** [comment]
Funguje, uzavřeno.
