### ISSUE TITLE
Heureka - změna skriptu pro měření konverzí

### ISSUE THREAD

**Issue by pavelevap** [pavelevap/ceske-sluzby#3]
Heuréka změnila implementační script pro měření konverzí a od 1.9.2015 již nenačítá konverze pomocí starší verze.

http://blog.heureka.cz/skript-mereni-konverzi-se-meni/

**Comment by lukasprelovsky** [comment]
Zmeneno

**Comment by pavelevap** [comment]
Díky moc, oprava použita. Mimochodem, stále se mi konverze bez problémů zobrazují, opravdu to přestalo fungovat?

**Comment by lukasprelovsky** [comment]
Zmena začne platiť 1. septembra 2015. Od tohto dátumu prestaneme aktuálny skript akceptovať a budeme spracovávať iba dáta zaslané prostredníctvom skriptu nového. V túto chviľu akceptujeme oba skripty.

http://blog.heureka.cz/skript-na-meranie-konverzii-sa-meni/ 

Možno to ešte nechali fičať, ale je dobré to upgradnúť ked to menia...

**Comment by pavelevap** [comment]
Ano, všiml jsem si data, ale ještě za říjen tam mám nějaké konverze, tak nevím. Každopádně nastal čas připravit novou verzi :-)
