### ISSUE TITLE
kompatibilita pluginu s PHP 7

### ISSUE THREAD

**Issue by lukasprelovsky** [pavelevap/ceske-sluzby#46]
co říkáte na kompatibilitu pluginu s php 7? Jeho rychlost má být o 50% více než u 5.x

https://make.wordpress.org/core/2015/09/10/wordpress-and-php7/

**Comment by pavelevap** [comment]
PHP 7 jsem zkoušel a opravdu je to rychlejší, myslím, že bude nová verze časem nasazována i na běžných hostinzích (bude to pro ně výhodné). Z 30 pluginů se objevily problémy u dvou starších pluginů, jinak vše fungovalo. Plugin České služby jsem ale zatím nezkoušel na PHP 7 :-) Nejsem si vědom, že by tam byla nějaká chyba, ale pokud na něco narazíte, tak dejte vědět...

**Comment by lukasprelovsky** [comment]
Tak php 7 již nasadili na hodne hostingech když to má už i endora.cz tak to musí mít všichni: D

**Comment by lukasprelovsky** [comment]
Odtestováno na PHP 7 , funkční :)

**Comment by pavelevap** [comment]
Díky, uzavírám :-)
