### ISSUE TITLE
Heureka - certifikát spokojenosti

### ISSUE THREAD

**Issue by pavelevap** [pavelevap/ceske-sluzby#50]
Implementace widgetu by měla být velmi jednoduchá.

V nastavení bude pouze možnost vlevo/vpravo + hodnota posunutí shora. Použit musí být také API klíč pro měření konverzí.

**Comment by lukasprelovsky** [comment]
Tohle treba :)

**Comment by pavelevap** [comment]
Integrováno: https://github.com/pavelevap/ceske-sluzby/commit/f50c031c91de5f028dec0d266b691b69fd7607bd

Zájemci mohou vyzkoušet :-)

**Comment by lukasprelovsky** [comment]
Odtestováno a po zmene https://github.com/pavelevap/ceske-sluzby/commit/e0fe6d0f81306c566b7038af5061d11d686d5690 funkcny.

**Comment by pavelevap** [comment]
Perfektní, uzavírám jako hotové.
