### ISSUE TITLE
DPD - obecné nastavení dopravy

### ISSUE THREAD

**Issue by novetrendy** [pavelevap/ceske-sluzby#58]
[woo-dpd.zip](https://github.com/pavelevap/ceske-sluzby/files/101913/woo-dpd.zip)
Třída pro dopravu DPD, bez možnosti výběru poboček.
Pro některé eshopy nutné.

**Comment by pavelevap** [comment]
@novetrendy: K čemu je to dobré? To může být nastaveno jako klasický způsob dopravy a nemusí mít žádnou speciální třídu?

**Comment by novetrendy** [comment]
Je to dobré, když má eshop hodně doprav, tak si na každou dopravu udělám třídu. 
Např.: Česká pošta balík do ruky, Česká pošta balík na poštu, Intime, PPL, PPL nadměrné zboží atd.
U každé třídy pak můžu zadávat různé poplatky, různou cenu a vybrat platební bránu.

**Comment by pavelevap** [comment]
K tomu by mělo stačit hned první nastavení dopravy Flat rate?

`wp-admin/admin.php?page=wc-settings&tab=shipping&section=wc_shipping_flat_rate`

**Comment by novetrendy** [comment]
Flat Rate umožní jen jednu cenu.
Potřebuji pro každou z doprav jinou cenu za dopravu a jinou pro dobírku.

**Comment by pavelevap** [comment]
K tomu tam je to poslední pole pro další sazby? A cenu pro dobírku lez nastavit pomocí pluginu WooCommerce Pay for Payment? Myslím, že jsem to tak dělal, ale možná mi něco uniká...

**Comment by novetrendy** [comment]
Asi něco uniká mě :-1: 
Poslední pole je cena za dopravu, já těch doprav potřebuji více, jak jsem psal.

![flat_rate](https://cloud.githubusercontent.com/assets/15211794/12556172/e2057a64-c384-11e5-8d24-0407c37fbf1d.jpg)

**Comment by pavelevap** [comment]
Aha, tak to bylo pro nové instalace odebráno ve WooCommerce 2.4: https://woocommerce.wordpress.com/2015/06/16/simplifying-flat-rate-shipping-in-wc-2-4/

Každopádně lze další možnosti snadno přidat pomocí `woocommerce_flat_rate_shipping_add_rate` (viz odkaz výše). Ale nevím, jestli už není nějaký jednodušší způsob... Každopádně přidání vlastní třídy jen pro nastavení názvu a ceny mi přijde zbytečně složité (i když se mohu mýlit)...

**Comment by novetrendy** [comment]
Já už mám ty třídy (ve formě pluginů) hotové a podle požadavků zákazníka jen nahraji, aktivuji a nastavím cenu. Do budoucnosti počítám s jedním pluginem, kde se bude dát vybrat jen doprava, kterou zákazník požaduje. Velká úspora času a je to jednoduché.

**Comment by pavelevap** [comment]
Jasné, ale podle mě je zbytečné, aby pro každou možnost existovala speciální třída, když to lze nastavit v administraci (a je tma pouze cena za dopravu a dobírku). Ale určitě by bylo vhodné asi nějak defaultně umožnit pro všechny eshopy, protože WooCommerce to moc snadno nepodporuje... Necháme to na příští verzi...

**Comment by pavelevap** [comment]
@novetrendy: Pokud nemá DPD nějaké specifické nastavení dopravy, tak je podle mě zbytečné mít vlastní třídu.

Vše je možné nastavit v rámci dopravních zón + nové funkce pluginu České služby:
- Nastavení poplatku za platbu (dobírka) #166 
- Možnost nastavení dostupných platebních metod #35
- Různá nastavení EET #122 
- Možnost nastavení zaokrouhlování #153 
- A ještě zkusíme nějak dořešit nastavení dopravy zdarma #17

Pokud by bylo potřeba doplnit nějaké další nastavení, tak to není problém, máme pro to už připravené funkce, ale nové možnosti nastavení jsou velmi flexibilní a myslím, že s nimi jde nastavit už téměř všechno :-) A pokud ne, tak dejte vědět, doplním.
