### ISSUE TITLE
XML: Produkt obsahuje shortcodes

### ISSUE THREAD

**Issue by pavelevap** [pavelevap/ceske-sluzby#65]
Co s popisem produktu, který obsahuje shortcodes (např. Visual Composer)?

**Comment by novetrendy** [comment]
Asi přidat options, kde si uživatel vybere, jestli spouštět, nebo vynechat s popisu.
Původně jsem myslel automaticky spouštět, ale někdo může mít v popisu třeba shortcode s social sharing apod.

**Comment by pavelevap** [comment]
Pořád si nejsem jist, sdílecí tlačítka by měla být řešena spíše hromadně na úrovni šablony, asi je nikdo nebude vkládat po jednom u každého produktu? Ale máte pravdu, jsou dvě možnosti a asi bude nejlepší to nechat na uživateli:

- Ignorovat zkrácené zápisy (odebrat je z popisu)
- Spustit je a následně výsledek očistit o HTML

**Comment by novetrendy** [comment]
Toto bude nejlepší řešení.

**Comment by pavelevap** [comment]
Zkusíme to, nemělo by to nic rozbít, možnost nastavení jsem doplnil.
