### ISSUE TITLE
Chyba 404

### ISSUE THREAD

**Issue by Kocarik** [pavelevap/ceske-sluzby#73]
Zdravim

Pri najnovsej verzii ktoru som stiahol, nevygeneruje ziaden XML Feed.

Po vygenerovani dam zobrazit subor, a hodi chybu 404 , konkretnejsie tuto : https://www.tisha.sk/wp-content/heureka.xml

**Comment by novetrendy** [comment]
Pokud máte hodně produktů, nějakou chvíli trvá, než se soubor vygeneruje.
Na adrese https://www.tisha.sk/?feed=heureka feed je?

**Comment by pavelevap** [comment]
@Kocarik: Díky za report! Zajímavé, průběžný feed funguje, ale generovaný soubor není k nalezení. Můžete zkontrolovat na FTP, zda tam opravdu ve složce `wp-content` není? Nemá tato složka nějaký restriktivní CHMOD? Nepoužíváte nějaký speciální bezpečnostní plugin? Máte v nastavení pluginu u Heureky zaškrtnuto "Aktivovat feed"?

**Comment by Kocarik** [comment]
Funguje to uz vsetko, mal esohp asi len cca 200 produktov, a tak po 15 min to az vygenerovalo.

Dakujem.
