### ISSUE TITLE
Zásilkovna

### ISSUE THREAD

**Issue by novetrendy** [pavelevap/ceske-sluzby#94]
Dobrý den,
bylo by možné přidat podporu pro zasilkovna.cz ?

**Comment by pavelevap** [comment]
Duplicita: #15.

Ano, v příští verzi musím trochu předělat a doplnit způsoby dopravy (např. podpora shipping zones).

**Comment by josejumbo** [comment]
Kdy bude Zásilkovna obsažena v balíčku české služby? Děkuji.

**Comment by pavelevap** [comment]
@josejumbo: Slibovat to nechci :-) ale chtěl bych ji integrovat cca v horizontu měsíce.

**Comment by novetrendy** [comment]
Dobrý den, jak je daleko zásilkovna?

**Comment by pavelevap** [comment]
@novetrendy: Zatím jsem se k tomu nedostal :-( Nechci raději nic slibovat, ale je to rozpracované...

**Comment by vvvamik** [comment]
> 
> 
> @novetrendy: Zatím jsem se k tomu nedostal :-( Nechci raději nic slibovat, ale je to rozpracované...

Dobrý den, už je funkčí Zásilkovna v pluginu České služby? Použvám Verze: 0.6-alpha. Děkuji.
